<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmartFileOrganizer.Domain\SmartFileOrganizer.Domain.csproj" />
    <ProjectReference Include="..\SmartFileOrganizer.Application\SmartFileOrganizer.Application.csproj" />
    <ProjectReference Include="..\SmartFileOrganizer.Infrastructure\SmartFileOrganizer.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartFileOrganizer.Scanning\SmartFileOrganizer.Scanning.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup Condition=" '$([MSBuild]::IsOsPlatform(Windows))' ">
    <DocnetRuntime>win-x64</DocnetRuntime>
  </PropertyGroup>

  <PropertyGroup Condition=" '$([MSBuild]::IsOsPlatform(Linux))' ">
    <DocnetRuntime>linux</DocnetRuntime>
  </PropertyGroup>

  <PropertyGroup Condition=" '$([MSBuild]::IsOsPlatform(OSX))' ">
    <DocnetRuntime>osx</DocnetRuntime>
  </PropertyGroup>

</Project>
